"""init

Revision ID: b3e6a6015c42
Revises: 52d97b556984
Create Date: 2021-11-28 17:12:10.708362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e6a6015c42'
down_revision = '52d97b556984'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
